using MailKit.Net.Smtp;
using MimeKit;

namespace ZaptecUsageReport.Services;

public class EmailService
{
    private readonly string _smtpServer;
    private readonly int _smtpPort;
    private readonly string _username;
    private readonly string _password;
    private readonly bool _useSsl;
    private readonly string _fromEmail;
    private readonly string _fromName;

    public EmailService(string smtpServer, int smtpPort, string username, string password, bool useSsl, string fromEmail, string fromName)
    {
        _smtpServer = smtpServer;
        _smtpPort = smtpPort;
        _username = username;
        _password = password;
        _useSsl = useSsl;
        _fromEmail = fromEmail;
        _fromName = fromName;
    }

    public async Task SendReportEmailAsync(
        string[] toEmails,
        string subject,
        string bodyText,
        string attachmentPath,
        string attachmentFileName,
        string[]? ccEmails = null,
        string[]? bccEmails = null)
    {
        // Call the multi-attachment method with a single attachment
        await SendReportEmailWithAttachmentsAsync(
            toEmails,
            subject,
            bodyText,
            new[] { (attachmentPath, attachmentFileName) },
            ccEmails,
            bccEmails
        );
    }

    public async Task SendReportEmailWithAttachmentsAsync(
        string[] toEmails,
        string subject,
        string bodyText,
        (string filePath, string fileName)[] attachments,
        string[]? ccEmails = null,
        string[]? bccEmails = null)
    {
        var message = new MimeMessage();
        message.From.Add(new MailboxAddress(_fromName, _fromEmail));

        // Add recipients
        foreach (var email in toEmails)
        {
            message.To.Add(MailboxAddress.Parse(email));
        }

        // Add CC recipients
        if (ccEmails != null)
        {
            foreach (var email in ccEmails)
            {
                message.Cc.Add(MailboxAddress.Parse(email));
            }
        }

        // Add BCC recipients
        if (bccEmails != null)
        {
            foreach (var email in bccEmails)
            {
                message.Bcc.Add(MailboxAddress.Parse(email));
            }
        }

        message.Subject = subject;

        // Create message body
        var builder = new BodyBuilder
        {
            TextBody = bodyText
        };

        // Attach all files
        foreach (var (filePath, fileName) in attachments)
        {
            if (File.Exists(filePath))
            {
                builder.Attachments.Add(fileName, File.ReadAllBytes(filePath));
            }
            else
            {
                throw new FileNotFoundException($"Attachment file not found: {filePath}");
            }
        }

        message.Body = builder.ToMessageBody();

        // Send the email
        using var client = new SmtpClient();
        try
        {
            await client.ConnectAsync(_smtpServer, _smtpPort, _useSsl);
            await client.AuthenticateAsync(_username, _password);
            await client.SendAsync(message);
            await client.DisconnectAsync(true);
        }
        catch (Exception ex)
        {
            throw new Exception($"Failed to send email: {ex.Message}", ex);
        }
    }

    public static string GenerateReportEmailBody(
        string installationName,
        DateTime fromDate,
        DateTime toDate,
        int sessionCount,
        double totalEnergy,
        double totalDuration,
        bool hasExcel = true,
        bool hasPdf = true)
    {
        var durationTimeSpan = TimeSpan.FromSeconds(totalDuration);

        var attachmentText = (hasExcel, hasPdf) switch
        {
            (true, true) => "Please find the detailed report attached as Excel and PDF files.",
            (true, false) => "Please find the detailed report attached as an Excel file.",
            (false, true) => "Please find the detailed report attached as a PDF file.",
            _ => ""
        };

        return $@"Zaptec Usage Report

Installation: {installationName}
Report Period: {fromDate:dd.MM.yyyy} to {toDate:dd.MM.yyyy}

Summary:
- Total Sessions: {sessionCount}
- Total Energy: {totalEnergy:F2} kWh
- Total Duration: {durationTimeSpan.Days}d {durationTimeSpan.Hours:D2}h {durationTimeSpan.Minutes:D2}m

{attachmentText}

---
This is an automated report generated by Zaptec Usage Report service.
";
    }
}
